const DEMO_PRODUCTS=[
{id:1,name:'Philips Airfryer XL 6,2L',brand:'Philips',category:'Keuken',price:79.95,oldPrice:99.95,shops:5,rating:4.7,tag:'Beste prijs',query:'airfryer',updated:'Vandaag'},
{id:2,name:'Sony WH-1000XM5 draadloze koptelefoon',brand:'Sony',category:'Elektronica',price:249,oldPrice:319,shops:8,rating:4.8,tag:'Beste deal',query:'koptelefoon',updated:'Vandaag'},
{id:3,name:'Samsung Galaxy A56 5G 128GB',brand:'Samsung',category:'Smartphones',price:349,oldPrice:429,shops:11,rating:4.6,tag:'Goedkoopste',query:'smartphone',updated:'Vandaag'},
{id:4,name:'LG 55 inch 4K Smart TV',brand:'LG',category:'Televisies',price:449,oldPrice:599,shops:7,rating:4.5,tag:'Beste deal',query:'televisie',updated:'Vandaag'},
{id:5,name:'LEGO Technic auto',brand:'LEGO',category:'Speelgoed',price:54.99,oldPrice:69.99,shops:6,rating:4.9,tag:'Beste prijs',query:'lego speelgoed',updated:'Vandaag'},
{id:6,name:'Bosch accuboormachine 18V',brand:'Bosch',category:'Doe-het-zelf',price:129,oldPrice:159,shops:9,rating:4.7,tag:'Goedkoopste',query:'boormachine',updated:'Vandaag'}
];
let products=[...DEMO_PRODUCTS];
const fmt=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(n)):'—';
const discount=d=>d.oldPrice>0&&d.price>=0?Math.max(0,Math.round((1-d.price/d.oldPrice)*100)):0;
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function card(d){const rating=Number.isFinite(Number(d.rating))?` · ★ ${escapeHtml(d.rating)}`:'';const shops=Number.isFinite(Number(d.shops))?`${d.shops} winkels`:'';const saving=d.oldPrice>d.price?`Bespaar ${fmt(d.oldPrice-d.price)} · -${discount(d)}%`:'';const updated=d.updated?` · bijgewerkt ${escapeHtml(d.updated)}`:'';return `<article class="deal-card"><div class="deal-visual">${escapeHtml(d.brand||'KoopRader')}</div><div class="deal-body"><span class="badge">${escapeHtml(d.tag||'Vergelijk')}</span><h3>${escapeHtml(d.name)}</h3><div class="shop">${escapeHtml(d.category||'')}${rating}${shops?' · '+escapeHtml(shops):''}</div><div class="prices"><strong>${fmt(d.price)}</strong>${d.oldPrice>d.price?`<del>${fmt(d.oldPrice)}</del>`:''}</div><div class="saving">${escapeHtml(saving)}${escapeHtml(updated)}</div><button class="deal-btn" data-id="${escapeHtml(d.id)}">Bekijk prijsvergelijking <span>→</span></button></div></article>`}
function render(list){const grid=document.querySelector('#dealGrid');grid.innerHTML=list.map(card).join('');document.querySelector('#resultCount').textContent=`${list.length} ${list.length===1?'resultaat':'resultaten'}`;document.querySelector('#empty').hidden=list.length!==0}
function sortList(list,mode){return [...list].sort((a,b)=>mode==='saving'?((b.oldPrice||b.price)-(b.price||0))-((a.oldPrice||a.price)-(a.price||0)):mode==='name'?String(a.name).localeCompare(String(b.name),'nl'):(a.price??Infinity)-(b.price??Infinity))}
function localSearch(q){q=q.trim().toLowerCase();if(!q){render(products);return}render(products.filter(d=>(d.name+' '+d.category+' '+d.brand+' '+(d.query||'')).toLowerCase().includes(q)));document.querySelector('#deals').scrollIntoView({behavior:'smooth'})}
function normalizeOffer(o){if(!o)return null;const price=Number(o.price);const shipping=Number(o.shipping_cost??o.shippingCost??0);return {...o,price:Number.isFinite(price)?price:null,shipping_cost:Number.isFinite(shipping)?shipping:0,total_price:Number.isFinite(Number(o.total_price))?Number(o.total_price):(Number.isFinite(price)?price+(Number.isFinite(shipping)?shipping:0):null),shop_name:o.shop_name||o.shop?.name||o.shop||'Winkel',shop_domain:o.shop_domain||o.shop?.domain||'',product_url:o.product_url||o.url||'#'}}
function normalizeProduct(p){const offers=Array.isArray(p.offers)?p.offers.map(normalizeOffer).filter(Boolean).sort((a,b)=>(a.total_price??Infinity)-(b.total_price??Infinity)):[];const lowest=Number(p.lowest_total_price??p.price);const price=Number.isFinite(lowest)?lowest:(offers[0]?.total_price??null);const old=Number(p.old_price);const shopCount=Number(p.shop_count??p.shops??offers.length);const updated=p.last_updated||p.last_checked_at||p.updated_at||'';return {...p,id:p.id,name:p.name||'Onbekend product',brand:p.brand||'',category:p.category||'',price,oldPrice:Number.isFinite(old)&&old>price?old:null,shops:Number.isFinite(shopCount)?shopCount:0,rating:Number.isFinite(Number(p.rating))?Number(p.rating):null,tag:p.tag||'Vergelijk',updated,offers}}
async function apiSearch(q,category='',sort='price'){const base=window.KOOPRADER_API_URL;if(!base)return null;try{const url=new URL(`${base.replace(/\/$/,'')}/api/search`);if(q)url.searchParams.set('q',q);if(category)url.searchParams.set('category',category);if(sort)url.searchParams.set('sort',sort);const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('API');const data=await r.json();return Array.isArray(data.products)?data.products.map(normalizeProduct):null}catch(e){return null}}
async function apiProduct(id){const base=window.KOOPRADER_API_URL;if(!base||id==null)return null;try{const url=new URL(`${base.replace(/\/$/,'')}/api/products/${encodeURIComponent(id)}`);const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('API');return normalizeProduct(await r.json())}catch(e){return null}}
function modalOffer(o){const total=Number.isFinite(Number(o.total_price))?fmt(Number(o.total_price)):fmt(Number(o.price));const shipping=Number(o.shipping_cost)>0?` + ${fmt(Number(o.shipping_cost))} verzending`:'';const stock=o.stock_status?` · ${escapeHtml(o.stock_status)}`:'';return `<div class="offer"><div><b>${escapeHtml(o.shop_name)}</b><small>${total}${escapeHtml(shipping)}${stock}</small></div><a class="deal-btn" href="${escapeHtml(o.product_url||'#')}" target="_blank" rel="nofollow sponsored noopener">Naar winkel →</a></div>`}
function showProduct(d){const existing=document.querySelector('#productModal');if(existing)existing.remove();const offers=Array.isArray(d.offers)?d.offers:[];const offerHtml=offers.length?`<h3>Actuele aanbiedingen</h3><div class="offers">${offers.map(modalOffer).join('')}</div>`:`<p class="modal-note">Er zijn op dit moment geen actuele aanbiedingen beschikbaar. Probeer later opnieuw.</p>`;const rating=Number.isFinite(Number(d.rating))?`<div><b>★ ${escapeHtml(d.rating)}</b><small>beoordeling</small></div>`:'';const modal=document.createElement('div');modal.id='productModal';modal.className='modal';modal.innerHTML=`<div class="modal-card"><button class="close" aria-label="Sluiten">×</button><span class="badge">${escapeHtml(d.tag||'Vergelijk')}</span><h2>${escapeHtml(d.name)}</h2><p>${escapeHtml(d.brand)} · ${escapeHtml(d.category)}</p><div class="modal-price">${d.price!=null?`Vanaf ${fmt(d.price)}`:'Prijs niet beschikbaar'}</div><div class="modal-grid"><div><b>${escapeHtml(d.shops||0)}</b><small>winkels</small></div><div><b>${d.oldPrice>d.price?`-${discount(d)}%`:'—'}</b><small>besparing</small></div>${rating}</div>${offerHtml}<button class="deal-btn close-action">Terug naar resultaten</button></div>`;document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('.close')||e.target.closest('.close-action'))modal.remove()})}
async function openProduct(d){const fresh=await apiProduct(d.id);showProduct(fresh||d)}
function applyUrlSearch(){const q=new URLSearchParams(location.search).get('q')?.trim();if(!q)return;document.querySelector('#searchInput').value=q;return apiSearch(q,'',document.querySelector('#sortSelect').value).then(remote=>{if(remote){products=remote;render(sortList(products,document.querySelector('#sortSelect').value))}else localSearch(q);document.querySelector('#deals').scrollIntoView({behavior:'smooth'})})}
document.addEventListener('DOMContentLoaded',()=>{render(products);document.querySelector('#year').textContent=new Date().getFullYear();applyUrlSearch();const form=document.querySelector('#searchForm');form.addEventListener('submit',async e=>{e.preventDefault();const q=document.querySelector('#searchInput').value.trim();const sort=document.querySelector('#sortSelect').value;history.replaceState(null,'',q?`?q=${encodeURIComponent(q)}`:location.pathname);const remote=await apiSearch(q,'',sort);if(remote){products=remote;render(sortList(products,sort));document.querySelector('#deals').scrollIntoView({behavior:'smooth'})}else localSearch(q)});document.querySelectorAll('[data-search]').forEach(x=>x.addEventListener('click',async()=>{const q=x.dataset.search;document.querySelector('#searchInput').value=q;history.replaceState(null,'',`?q=${encodeURIComponent(q)}`);const remote=await apiSearch(q,'',document.querySelector('#sortSelect').value);if(remote){products=remote;render(sortList(products,document.querySelector('#sortSelect').value));document.querySelector('#deals').scrollIntoView({behavior:'smooth'})}else localSearch(q)}));document.querySelector('#sortSelect').addEventListener('change',e=>render(sortList(products,e.target.value)));document.addEventListener('click',e=>{const b=e.target.closest('.deal-btn[data-id]');if(!b)return;const d=products.find(x=>String(x.id)===String(b.dataset.id));if(d)openProduct(d)});});
