const DEMO_PRODUCTS=[
{id:1,name:'Philips Airfryer XL 6,2L',brand:'Philips',category:'Keuken',price:79.95,oldPrice:99.95,shops:5,rating:4.7,tag:'Beste prijs',query:'airfryer',updated:'Vandaag'},
{id:2,name:'Sony WH-1000XM5 draadloze koptelefoon',brand:'Sony',category:'Elektronica',price:249,oldPrice:319,shops:8,rating:4.8,tag:'Beste deal',query:'koptelefoon',updated:'Vandaag'},
{id:3,name:'Samsung Galaxy A56 5G 128GB',brand:'Samsung',category:'Smartphones',price:349,oldPrice:429,shops:11,rating:4.6,tag:'Goedkoopste',query:'smartphone',updated:'Vandaag'},
{id:4,name:'LG 55 inch 4K Smart TV',brand:'LG',category:'Televisies',price:449,oldPrice:599,shops:7,rating:4.5,tag:'Beste deal',query:'televisie',updated:'Vandaag'},
{id:5,name:'LEGO Technic auto',brand:'LEGO',category:'Speelgoed',price:54.99,oldPrice:69.99,shops:6,rating:4.9,tag:'Beste prijs',query:'lego speelgoed',updated:'Vandaag'},
{id:6,name:'Bosch accuboormachine 18V',brand:'Bosch',category:'Doe-het-zelf',price:129,oldPrice:159,shops:9,rating:4.7,tag:'Goedkoopste',query:'boormachine',updated:'Vandaag'}
];
let products=[...DEMO_PRODUCTS];
const fmt=n=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(n);
const discount=d=>Math.max(0,Math.round((1-d.price/d.oldPrice)*100));
function card(d){return `<article class="deal-card"><div class="deal-visual">${d.brand}</div><div class="deal-body"><span class="badge">${d.tag}</span><h3>${escapeHtml(d.name)}</h3><div class="shop">${escapeHtml(d.category)} · ★ ${d.rating} · ${d.shops} winkels</div><div class="prices"><strong>${fmt(d.price)}</strong><del>${fmt(d.oldPrice)}</del></div><div class="saving">Bespaar ${fmt(d.oldPrice-d.price)} · -${discount(d)}% · bijgewerkt ${d.updated}</div><button class="deal-btn" data-id="${d.id}">Bekijk prijsvergelijking <span>→</span></button></div></article>`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(list){document.querySelector('#dealGrid').innerHTML=list.map(card).join('');document.querySelector('#resultCount').textContent=`${list.length} ${list.length===1?'resultaat':'resultaten'}`;document.querySelector('#empty').hidden=list.length!==0}
function sortList(list,mode){return [...list].sort((a,b)=>mode==='saving'?(b.oldPrice-b.price)-(a.oldPrice-a.price):mode==='name'?a.name.localeCompare(b.name,'nl'):(a.price-b.price))}
function search(q){q=q.trim().toLowerCase();if(!q){render(products);return}render(products.filter(d=>(d.name+' '+d.category+' '+d.brand+' '+d.query).toLowerCase().includes(q)));document.querySelector('#deals').scrollIntoView({behavior:'smooth'})}
async function apiSearch(q){const base=window.KOOPRADER_API_URL;if(!base)return null;try{const r=await fetch(`${base}/api/search?q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('API');const data=await r.json();return Array.isArray(data.products)?data.products:null}catch(e){return null}}
document.addEventListener('DOMContentLoaded',()=>{render(products);document.querySelector('#year').textContent=new Date().getFullYear();document.querySelector('#searchForm').addEventListener('submit',async e=>{e.preventDefault();const q=document.querySelector('#searchInput').value;const remote=await apiSearch(q);if(remote){products=remote;render(products)}else search(q)});document.querySelectorAll('[data-search]').forEach(x=>x.addEventListener('click',()=>{const q=x.dataset.search;document.querySelector('#searchInput').value=q;search(q)}));document.querySelector('#sortSelect').addEventListener('change',e=>render(sortList(products,e.target.value)));document.addEventListener('click',e=>{const b=e.target.closest('.deal-btn');if(!b)return;const d=products.find(x=>String(x.id)===String(b.dataset.id));if(d)showProduct(d)});});
function showProduct(d){const existing=document.querySelector('#productModal');if(existing)existing.remove();const modal=document.createElement('div');modal.id='productModal';modal.className='modal';modal.innerHTML=`<div class="modal-card"><button class="close" aria-label="Sluiten">×</button><span class="badge">${escapeHtml(d.tag)}</span><h2>${escapeHtml(d.name)}</h2><p>${escapeHtml(d.brand)} · ${escapeHtml(d.category)}</p><div class="modal-price">Vanaf ${fmt(d.price)}</div><div class="modal-grid"><div><b>${d.shops}</b><small>winkels</small></div><div><b>-${discount(d)}%</b><small>besparing</small></div><div><b>★ ${d.rating}</b><small>beoordeling</small></div></div><p class="modal-note">Dit is een productvergelijking. In de productieversie worden hier actuele aanbiedingen, verzendkosten, voorraad en winkel-links vanuit de KoopRader API geladen.</p><button class="deal-btn close-action">Terug naar resultaten</button></div>`;document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('.close')||e.target.closest('.close-action'))modal.remove()})}
